apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesJson6902:
  - path: ingress_cms_auth_patch.yaml
    target:
      group: extensions
      kind: Ingress
      name: cms-auth
      version: v1beta1
  - path: ingress_cms_patch.yaml
    target:
      group: extensions
      kind: Ingress
      name: cms
      version: v1beta1
